### PR TITLE
Add general-store to the featured repos list

### PR DESCRIPTION
**Pull request by colbyr**
Adds [general-store](https://github.com/HubSpot/general-store) to the list of things with icons.

screen shot 2015-02-25 at 3 14 44 pm

cc @graysky

### CODE REVIEW

**Comment by adamschwartz** [comment]
Nice icon.

**Comment by adamschwartz** [comment]
FYI, clicking “General Store” takes you to a [dead link](http://github.hubspot.com/general-store) though.

**Comment by colbyr** [comment]
@adamschwartz dead link is fixed. thanks for the heads up

**Comment by adamschwartz** [comment]
np, nice page!

**Comment by timmfin** [comment]
Credit to @cbathurst for the sweet icon :smile_cat:

**Pull request merged**
